# Generated by Django 5.1.6 on 2025-02-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logapp", "0002_rename_content_logentry_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="message",
            field=models.TextField(null=True),
        ),
    ]
