# Generated by Django 5.1.6 on 2025-02-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logapp", "0004_alter_logentry_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="timestamp",
            field=models.DateTimeField(null=True),
        ),
    ]
