name: Periodic Django Management Commands

on:
  schedule:
    - cron: "0 */24 * * *"  # Runs at 0th min past every 1 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true  # Required for pushing changes
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Import Logs Command
      working-directory: ./logflowai
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py import_logs
    - name: Execute Agentic Report Creation Command
      working-directory: ./logflowai
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python manage.py run_orchestrator    
    - name: Execute Scrapybara Email Command
      working-directory: ./logflowai
      env:
        SCRAPY_KEY: ${{ secrets.SCRAPY_KEY }}
        OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
      run: python manage.py execute_scrapybara_email
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit --allow-empty -m "ran periodic workflow for db update"
        git push
